In [65]:
import sys
import numpy as np

In [3]:
v_array = np.array([1,2,3])

In [6]:
print(v_array)

[1 2 3]


In [7]:
v_array.shape

(3,)

In [9]:
v_matrix = np.array([[1,2,3],[4,5,6]])

In [12]:
v_matrix.ndim # Ver cuantas dimensiones tiene el array

2

In [16]:
np.eye(10) #Matriz identidad

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.zeros((3,2)) #arrays de ceros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
np.ones((3,2)) #arrays de 5 elementos

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
np.random.random((3,4))

array([[0.49268892, 0.10857637, 0.6064112 , 0.84930129],
       [0.84574841, 0.13504799, 0.31257769, 0.66556546],
       [0.81171197, 0.59638318, 0.5936434 , 0.54800089]])

In [62]:
v_array_txt= np.genfromtxt('../Dataset/np_text.txt', delimiter=',')

In [44]:
v_array_txt.shape

(4, 3)

In [45]:
list_2d = [[1222,2222,2223],[5,23,4004]]

In [61]:
big_array = np.array(range(1000000))
big_list = list(range(1000000))

In [74]:
sys.getsizeof(big_array)

4000096

In [75]:
sys.getsizeof(big_list)

9000112

In [81]:
!cat '../Dataset/np_text.txt'

"cat" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.


In [78]:
array_id = np.array(range(12))

In [83]:
array_id[1]

1

In [84]:
array_id[:2] #Bota los 2 primeros elementos del array

array([0, 1])

In [86]:
array_id[::2] #Bota el array con saltos de 2 en 2

array([ 0,  2,  4,  6,  8, 10])

In [97]:
%%timeit -n 10 # Ver tiempo de ejecucion de la celda

sum(range(1000))

27.1 µs ± 371 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [98]:
%%timeit -n 10
np.sum(np.arange(1000))

47.6 µs ± 17.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
