Importa numpy

In [1]:
import numpy as np

crea un numpy array que tenga la siguente estructura

```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```

llamalo `array`

In [2]:
array = np.array([[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]])

averigua la forma del array

In [3]:
array.shape

(5, 3)

Selecciona la segunda columna del array

In [8]:
array[:,1]

array([ 6,  7,  8,  9, 10])

 Crea un vector con los valores del 15 al 55, llamalo array2
    
*pista: usa np.arange*

In [12]:
array2 = np.arange(15,55)

asigna el valor 23 a la quinta posicion del array2

In [13]:
array2[4] = 23

convierte array2 del revés (es decir `[55,54,....,15]`

In [27]:
array2 = np.flip(array2)


Crea una matriz diagonal donde los elementos de la diagonal sean los 5 primeros valores pares de array2, llamala `matriz_diag`

*pista: usa np.diag*

In [30]:
matriz_diag = np.diag(array2[0::2][:5])
matriz_diag

array([[54,  0,  0,  0,  0],
       [ 0, 52,  0,  0,  0],
       [ 0,  0, 50,  0,  0],
       [ 0,  0,  0, 48,  0],
       [ 0,  0,  0,  0, 46]])

Imprime el numero de dimensiones de `matriz_diag`

In [18]:
matriz_diag.ndim

2

Crea una matriz con números aleatorios de tamaño 5x3 (4 filas por 3 columnas), llamala `matriz`

In [31]:
matriz = np.random.random((5,3))

multiplica `matriz` por `matriz_diag`

In [34]:
matriz_diag@matriz

array([[38.63108536, 10.7513219 , 37.71660931],
       [ 1.76669886, 25.61531568, 27.29603261],
       [12.70123045, 32.15433318, 17.6695164 ],
       [27.29289101, 25.30808438, 33.39080099],
       [31.09069661, 21.69686473, 29.05778775]])

In [35]:
matriz.T@matriz_diag

array([[38.63108536,  1.76669886, 12.70123045, 27.29289101, 31.09069661],
       [10.7513219 , 25.61531568, 32.15433318, 25.30808438, 21.69686473],
       [37.71660931, 27.29603261, 17.6695164 , 33.39080099, 29.05778775]])